language: python
python: '3.5'
cache: pip
sudo: true

notifications:
  email: false

script:
    - mkdocs build

before_install:
    - openssl aes-256-cbc -K $encrypted_daec469c0140_key -iv $encrypted_daec469c0140_iv
        -in .travis_key.enc -out .travis_key -d

after_success:
    - git config --global user.email "Moloquent@Travis"
    - git config --global user.name "Moloquent@Travis"
    - git config --global push.default simple
    - eval "$(ssh-agent -s)" #start the ssh agent
    - chmod 600 .travis_key # this key should have push access
    - ssh-add .travis_key
    - git clone git@github.com:moloquent/moloquent.github.io.git
    - cp -rv site/* moloquent.github.io
    - cd moloquent.github.io
    - git add --all
    - git commit -m "Travis CI"
    - git push
