site_name: Moloquent
site_url: https://moloquent.github.io
site_description: A MongoDB based Eloquent model and Query builder for Laravel (Moloquent)

repo_url: https://github.com/moloquent

remote_name: deploy
remote_branch: master

google_analytics: ['UA-83645466-1','moloquent.github.io']

theme_dir: theme

markdown_extensions:
    - toc:
        permalink: "#"
    - admonition:

pages:

- Master:
  - Welcome: master/index.md
  - Installation: master/installation.md
  - Eloquent: master/eloquent.md
  - Query Builder: master/builder.md
  - Schema: master/schema.md
  - Extensions:
    - Auth: master/extensions/auth.md
    - Queues: master/extensions/queue.md
    - Sentry: master/extensions/sentry.md
    - Session: master/extensions/session.md
  - Usage:
    - Basic: master/usage/basic.md
    - Advanced: master/usage/advanced.md
    - Relations: master/usage/relations.md
    - MongoDB specific: master/usage/mongodb.md
